"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v^(wr&hs9h(lx2za%02a-ta3s4(te$rb3zzxqu@-ypl_8ubm-l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG', default=1))

ALLOWED_HOSTS = [
    'localhost',
    'ffdraft-server-env.eba-tm9s2rtw.us-west-2.elasticbeanstalk.com',
    '7inthebox.com',
    'api.7inthebox.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'ffdraft'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'djongo',
        "CLIENT": {
            "name": 'ffdraft',
            "host": 'mongodb+srv://root:1234@ffdraft.scjqb.mongodb.net/ffdraft?retryWrites=true&w=majority',
            "username": 'root',
            "password": '1234',
            "authMechanism": "SCRAM-SHA-1"
        }
    }
}

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            "CLIENT": {
                "name": 'ffdraft-dev',
                "host": 'mongodb+srv://root:1234@ffdraft.scjqb.mongodb.net/ffdraft-dev?retryWrites=true&w=majority',
                "username": 'root',
                "password": '1234',
                "authMechanism": "SCRAM-SHA-1"
            }
        }
    }

# Authentication

# AUTHENTICATION_BACKENDS = (
#     'mongoengine.django.auth.MongoEngineBackend',
# )
#
# SESSION_ENGINE = 'mongoengine.django.sessions'
# SESSION_SERIALIZER = 'mongoengine.django.sessions.BSONSerializer'



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://ffdraft-client.s3-website-us-west-2.amazonaws.com',
    'https://ffdraft-client.s3-website-us-west-2.amazonaws.com',
    'http://d3u3j54quw8zdo.cloudfront.net',
    'https://d3u3j54quw8zdo.cloudfront.net',
    'http://7inthebox.com',
    'https://7inthebox.com',
    'http://api.7inthebox.com',
    'https://api.7inthebox.com',
    'http://draftstrategysim.com/',
    'https://draftstrategysim.com/',
    'http://www.draftstrategysim.com/',
    'https://www.draftstrategysim.com/'
]

CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
