# Generated by Django 3.2.5 on 2021-07-10 22:54

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('scoring', models.CharField(default='PPR', max_length=30)),
                ('teams', models.PositiveIntegerField(default=12)),
                ('rounds', models.PositiveIntegerField(default=16)),
                ('distributions', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('scoring', models.CharField(default='PPR', max_length=30)),
                ('teams', models.PositiveIntegerField(default=12)),
                ('rounds', models.PositiveIntegerField(default=16)),
                ('pick', models.PositiveIntegerField(default=1)),
                ('score', models.FloatField(default=0)),
                ('players', djongo.models.fields.JSONField(null=True)),
                ('positions', djongo.models.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('color', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
